parameters:
    env(OAUTH_CLIENT_ID): ''
    env(OAUTH_CLIENT_SECRET): ''
    env(OAUTH_REDIRECT_URI): ''
    env(OAUTH_AUTHORIZE_URL): ''
    env(OAUTH_TOKEN_URL): ''
    env(OAUTH_USERINFO_URL): ''
    env(OAUTH_SCOPE): ''
    env(OAUTH_CODE_CHALLENGE_METHOD): 'S256'
    env(OAUTH_RESPONSE_TYPE): 'code'

symfony_oauth2:
    client_id: '%env(OAUTH_CLIENT_ID)%'
    client_secret: '%env(OAUTH_CLIENT_SECRET)%'
    redirect_uri: '%env(OAUTH_REDIRECT_URI)%'
    authorize_url: '%env(OAUTH_AUTHORIZE_URL)%'
    token_url: '%env(OAUTH_TOKEN_URL)%'
    userinfo_url: '%env(OAUTH_USERINFO_URL)%'
    scope: '%env(OAUTH_SCOPE)%' 